# Generated by Django 3.2.5 on 2021-08-14 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import places.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='Date posted')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('description', models.CharField(max_length=3000)),
                ('condition', models.CharField(choices=[('1', 'New'), ('2', 'Used')], max_length=20)),
                ('starting_price', models.FloatField(default=0.0)),
                ('last_bid', models.FloatField(default=0.0)),
                ('end_date', models.DateTimeField()),
                ('picture1', models.ImageField(default='placeholder.png', upload_to='')),
                ('picture2', models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='')),
                ('picture3', models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='')),
                ('picture4', models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='')),
                ('picture5', models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='')),
                ('picture6', models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('currency', models.CharField(choices=[('1', 'LEI'), ('2', 'USD (US$)'), ('3', 'EUR (€)'), ('4', 'GBP (£)')], max_length=20)),
                ('location', places.fields.PlacesField(max_length=255, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
