# Generated by Django 3.2.5 on 2021-08-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('1', 'Nou'), ('2', 'Folosit')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('1', 'LEI'), ('2', 'USD (US$)'), ('3', 'EURO (€)'), ('4', 'LIRE (£)')], max_length=20),
        ),
    ]
