# Generated by Django 3.2.5 on 2021-08-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210819_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='finished_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
